
import { PlaceHolderImages, type ImagePlaceholder } from './placeholder-images';

export interface Restaurant {
  id: string;
  name: string;
  cuisine: string;
  description: string;
  address: string;
  phone: string;
  category: 'Veg' | 'Non-Veg' | 'Mixed';
  location: {
    lat: number;
    lng: number;
  };
  heroImage: ImagePlaceholder;
  gallery: ImagePlaceholder[];
}

const findImage = (id: string): ImagePlaceholder => {
    const image = PlaceHolderImages.find(img => img.id === id);
    if (!image) {
        // Fallback for missing images to prevent crashes
        console.error(`Image with id ${id} not found`);
        return {
          id: 'fallback',
          description: 'Image not found',
          imageUrl: 'https://placehold.co/800x600?text=Image+Not+Found',
          imageHint: 'placeholder'
        };
    }
    return image;
}

const allRestaurants: Restaurant[] = [
  {
    id: 'verde-bistro',
    name: 'Verde Bistro',
    cuisine: 'Californian',
    category: 'Mixed',
    description: 'A bright, airy bistro focusing on fresh, locally-sourced ingredients. Perfect for brunch, lunch, and light dinners.',
    address: '123 Meadow Lane, Sunnyville, CA 94087',
    phone: '(408) 555-1234',
    location: { lat: 37.403, lng: -122.083 },
    heroImage: findImage('verde-hero'),
    gallery: [
      findImage('verde-gallery-1'),
      findImage('verde-gallery-2'),
    ],
  },
  {
    id: 'ember-and-ash',
    name: 'Ember & Ash',
    cuisine: 'Steakhouse',
    category: 'Non-Veg',
    description: 'A modern steakhouse with a rustic feel, known for its wood-fired grill and premium cuts of meat.',
    address: '456 Oak Street, Redwood City, CA 94063',
    phone: '(650) 555-5678',
    location: { lat: 37.485, lng: -122.232 },
    heroImage: findImage('ember-hero'),
    gallery: [
      findImage('ember-gallery-1'),
      findImage('ember-gallery-2'),
    ],
  },
  {
    id: 'azure-seafood',
    name: 'Azure Seafood',
    cuisine: 'Seafood',
    category: 'Non-Veg',
    description: 'An upscale seafood restaurant offering stunning waterfront views and the freshest catches of the day.',
    address: '789 Bayside Blvd, Marina Del Rey, CA 90292',
    phone: '(310) 555-9012',
    location: { lat: 33.980, lng: -118.451 },
    heroImage: findImage('azure-hero'),
    gallery: [
      findImage('azure-gallery-1'),
      findImage('azure-gallery-2'),
    ],
  },
  {
    id: 'terra-cotta',
    name: 'Terra Cotta',
    cuisine: 'Italian',
    category: 'Mixed',
    description: 'A cozy, traditional Italian trattoria serving handmade pasta and classic dishes in a warm, inviting atmosphere.',
    address: '101 Vineyard Ave, Napa, CA 94559',
    phone: '(707) 555-3456',
    location: { lat: 38.297, lng: -122.285 },
    heroImage: findImage('terra-hero'),
    gallery: [
      findImage('terra-gallery-1'),
      findImage('terra-gallery-2'),
    ],
  },
  {
    id: 'kayaloram-grand',
    name: 'Kayaloram Grand',
    cuisine: 'Kerala Seafood',
    category: 'Non-Veg',
    description: 'A beautiful restaurant on the backwaters serving authentic Kerala seafood delicacies.',
    address: 'Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 484 221 7777',
    location: { lat: 9.965, lng: 76.243 },
    heroImage: findImage('kayaloram-hero'),
    gallery: [
      findImage('kayaloram-gallery-1'),
      findImage('kayaloram-gallery-2'),
    ],
  },
  {
    id: 'malabar-kitchen',
    name: 'Malabar Kitchen',
    cuisine: 'South Indian',
    category: 'Mixed',
    description: 'Experience the rich and diverse flavors of Malabar cuisine, from delicious biryanis to traditional thalis.',
    address: 'Panampilly Nagar, Kochi, Kerala 682036, India',
    phone: '+91 484 231 4444',
    location: { lat: 9.96, lng: 76.29 },
    heroImage: findImage('malabar-hero'),
    gallery: [
      findImage('malabar-gallery-1'),
      findImage('malabar-gallery-2'),
    ],
  },
  {
    id: 'fort-house-restaurant',
    name: 'Fort House Restaurant',
    cuisine: 'Kerala & Continental',
    category: 'Mixed',
    description: 'A charming seaside restaurant known for its serene ambiance and delicious fusion cuisine.',
    address: '2/6A, Calvathy Road, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 484 221 7025',
    location: { lat: 9.969, lng: 76.242 },
    heroImage: findImage('fort-house-hero'),
    gallery: [
      findImage('fort-house-gallery-1'),
      findImage('fort-house-gallery-2'),
    ],
  },
  {
    id: 'dal-roti',
    name: 'Dal Roti',
    cuisine: 'North Indian',
    category: 'Mixed',
    description: 'Authentic North Indian food with a specialty in Kathi Rolls. A local favorite in Fort Kochi.',
    address: '1/293, Lilly Street, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 9847 519 059',
    location: { lat: 9.966, lng: 76.242 },
    heroImage: findImage('dal-roti-hero'),
    gallery: [
      findImage('dal-roti-gallery-1'),
      findImage('dal-roti-gallery-2'),
    ],
  },
  {
    id: 'kashi-art-cafe',
    name: 'Kashi Art Cafe',
    cuisine: 'Cafe & Contemporary',
    category: 'Veg',
    description: 'A unique space that combines an art gallery with a beautiful cafe, known for its breakfast and homemade cakes.',
    address: 'Burgher Street, Fort Nagar, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 484 221 5769',
    location: { lat: 9.964, lng: 76.244 },
    heroImage: findImage('kashi-cafe-hero'),
    gallery: [
      findImage('kashi-cafe-gallery-1'),
      findImage('kashi-cafe-gallery-2'),
    ],
  },
  {
    id: 'paragon-kochi',
    name: 'Paragon Restaurant',
    cuisine: 'Malabar, Kerala',
    category: 'Mixed',
    description: 'A legendary name in Kerala cuisine, famous for its traditional flavors and biryani.',
    address: 'Lulu Mall, Edapally, Kochi, Kerala 682024, India',
    phone: '+91 484 402 3333',
    location: { lat: 10.027, lng: 76.308 },
    heroImage: findImage('paragon-hero'),
    gallery: [
      findImage('paragon-gallery-1'),
      findImage('paragon-gallery-2'),
    ],
  },
  {
    id: 'fusion-bay',
    name: 'Fusion Bay',
    cuisine: 'Seafood, Kerala',
    category: 'Non-Veg',
    description: 'Specializing in fusion seafood dishes, offering a unique twist on local flavors.',
    address: 'KB Jacob Road, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 484 221 7444',
    location: { lat: 9.967, lng: 76.241 },
    heroImage: findImage('fusion-bay-hero'),
    gallery: [
      findImage('fusion-bay-gallery-1'),
      findImage('fusion-bay-gallery-2'),
    ],
  },
  {
    id: 'spice-harbour',
    name: 'Spice Harbour',
    cuisine: 'Multi-Cuisine',
    category: 'Mixed',
    description: 'A waterfront restaurant at a premium hotel, known for its extensive buffet and live cooking stations.',
    address: 'Casino Hotel, Willingdon Island, Kochi, Kerala 682003, India',
    phone: '+91 484 301 1500',
    location: { lat: 9.965, lng: 76.271 },
    heroImage: findImage('spice-harbour-hero'),
    gallery: [
      findImage('spice-harbour-gallery-1'),
      findImage('spice-harbour-gallery-2'),
    ],
  },
  {
    id: 'the-rice-boat',
    name: 'The Rice Boat',
    cuisine: 'Seafood, Fine Dining',
    category: 'Non-Veg',
    description: 'A luxury dining experience on a stationary "kettuvallam" boat, offering the best of local seafood.',
    address: 'Vivanta by Taj - Malabar, Willingdon Island, Kochi, Kerala 682009, India',
    phone: '+91 484 664 3000',
    location: { lat: 9.957, lng: 76.261 },
    heroImage: findImage('new-spot-4-hero'),
    gallery: [findImage('new-spot-4-gallery-1'), findImage('new-spot-4-gallery-2')],
  },
  {
    id: 'oceanos-restaurant',
    name: 'Oceanos Restaurant',
    cuisine: 'Seafood, Continental',
    category: 'Non-Veg',
    description: 'A highly-rated restaurant in Fort Kochi known for its fresh seafood and cozy ambiance.',
    address: 'Elphinstone Annexe, Beach Road, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 9995 822 082',
    location: { lat: 9.968, lng: 76.240 },
    heroImage: findImage('new-spot-6-hero'),
    gallery: [findImage('new-spot-6-gallery-1'), findImage('new-spot-6-gallery-2')],
  },
  {
    id: 'rahmathulla-hotel',
    name: 'Rahmathulla Hotel (Kayees)',
    cuisine: 'Biryani, Malabar',
    category: 'Non-Veg',
    description: 'An iconic spot in Kochi, celebrated for its authentic Mutton and Chicken Biryani.',
    address: 'Mattancherry, Kochi, Kerala 682002, India',
    phone: '+91 484 222 6080',
    location: { lat: 9.960, lng: 76.249 },
    heroImage: findImage('new-spot-32-hero'),
    gallery: [findImage('new-spot-32-gallery-1'), findImage('new-spot-32-gallery-2')],
  },
  {
    id: 'david-hall-gallery-cafe',
    name: 'David Hall Gallery Cafe',
    cuisine: 'Cafe, Continental',
    category: 'Mixed',
    description: 'A charming cafe set in a restored Dutch bungalow, also serving as an art gallery.',
    address: '1/264, Parade Ground, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 9188 120 270',
    location: { lat: 9.967, lng: 76.243 },
    heroImage: findImage('new-spot-33-hero'),
    gallery: [findImage('new-spot-33-gallery-1'), findImage('new-spot-33-gallery-2')],
  },
  {
    id: 'qissa-cafe',
    name: 'Qissa Cafe',
    cuisine: 'Cafe, Snacks',
    category: 'Mixed',
    description: 'A small, cozy cafe perfect for a quick bite, coffee, and conversation.',
    address: 'KB Jacob Rd, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 9562 100 051',
    location: { lat: 9.967, lng: 76.242 },
    heroImage: findImage('new-spot-2-hero'),
    gallery: [findImage('new-spot-2-gallery-1'), findImage('new-spot-2-gallery-2')],
  },
  {
    id: 'seagull-restaurant',
    name: 'Seagull Restaurant',
    cuisine: 'Seafood, Bar',
    category: 'Non-Veg',
    description: 'A popular bar and restaurant with a deck overlooking the sea, great for watching sunsets.',
    address: 'Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 484 221 6891',
    location: { lat: 9.970, lng: 76.241 },
    heroImage: findImage('new-spot-39-hero'),
    gallery: [findImage('new-spot-39-gallery-1'), findImage('new-spot-39-gallery-2')],
  },
  {
    id: 'the-asian-kitchen',
    name: 'The Asian Kitchen',
    cuisine: 'Pan-Asian',
    category: 'Mixed',
    description: 'A fine dining restaurant offering a range of cuisines from across Asia.',
    address: 'Kochi Marriott Hotel, Edapally, Kochi, Kerala 682024, India',
    phone: '+91 484 717 7777',
    location: { lat: 10.028, lng: 76.309 },
    heroImage: findImage('new-spot-9-hero'),
    gallery: [findImage('new-spot-9-gallery-1'), findImage('new-spot-9-gallery-2')],
  },
  {
    id: 'brindhavan-vegetarian',
    name: 'Brindhavan Vegetarian Restaurant',
    cuisine: 'South Indian, Vegetarian',
    category: 'Veg',
    description: 'A classic vegetarian restaurant serving delicious dosas, thalis, and other South Indian staples.',
    address: 'Palarivattom, Kochi, Kerala 682025, India',
    phone: '+91 484 234 4455',
    location: { lat: 10.007, lng: 76.307 },
    heroImage: findImage('new-spot-42-hero'),
    gallery: [findImage('new-spot-42-gallery-1'), findImage('new-spot-42-gallery-2')],
  },
  {
    id: 'mullapanthal-toddy',
    name: 'Mullapanthal Toddy Shop',
    cuisine: 'Toddy Shop, Kerala',
    category: 'Non-Veg',
    description: 'A famous toddy shop known for its authentic spicy Kerala food, especially seafood.',
    address: 'Udayamperoor, Kochi, Kerala 682307, India',
    phone: '+91 9846 142 000',
    location: { lat: 9.932, lng: 76.346 },
    heroImage: findImage('new-spot-31-hero'),
    gallery: [findImage('new-spot-31-gallery-1'), findImage('new-spot-31-gallery-2')],
  },
  {
    id: 'dhe-puttu',
    name: 'Dhe Puttu',
    cuisine: 'Kerala, Puttu Speciality',
    category: 'Mixed',
    description: 'A restaurant dedicated to "Puttu", a traditional Kerala dish, served in countless varieties.',
    address: 'Edapally, Kochi, Kerala 682024, India',
    phone: '+91 484 404 8444',
    location: { lat: 10.025, lng: 76.311 },
    heroImage: findImage('new-spot-34-hero'),
    gallery: [findImage('new-spot-34-gallery-1'), findImage('new-spot-34-gallery-2')],
  },
  {
    id: 'the-grill-lab',
    name: 'The Grill Lab',
    cuisine: 'Grill, BBQ',
    category: 'Non-Veg',
    description: 'A modern eatery focusing on grilled dishes, steaks, and burgers.',
    address: 'Kakkanad, Kochi, Kerala 682030, India',
    phone: '+91 7593 888 881',
    location: { lat: 10.016, lng: 76.362 },
    heroImage: findImage('new-spot-20-hero'),
    gallery: [findImage('new-spot-20-gallery-1'), findImage('new-spot-20-gallery-2')],
  },
  {
    id: 'pandhal-cafe',
    name: 'Pandhal Cafe & Deli',
    cuisine: 'Cafe, Continental',
    category: 'Mixed',
    description: 'A stylish cafe offering a great ambiance, coffee, and continental food.',
    address: 'Panampilly Nagar, Kochi, Kerala 682036, India',
    phone: '+91 484 232 2011',
    location: { lat: 9.961, lng: 76.293 },
    heroImage: findImage('new-spot-17-hero'),
    gallery: [findImage('new-spot-17-gallery-1'), findImage('new-spot-17-gallery-2')],
  },
  {
    id: 'nawras-seafood',
    name: 'Nawras Seafood Restaurant',
    cuisine: 'Seafood, Arabic',
    category: 'Non-Veg',
    description: 'A popular spot for fresh seafood cooked in Arabic and local styles.',
    address: 'Thoppumpady, Kochi, Kerala 682005, India',
    phone: '+91 9847 033 330',
    location: { lat: 9.944, lng: 76.262 },
    heroImage: findImage('new-spot-50-hero'),
    gallery: [findImage('new-spot-50-gallery-1'), findImage('new-spot-50-gallery-2')],
  },
  {
    id: 'kettuvallam-restaurant',
    name: 'Kettuvallam Restaurant',
    cuisine: 'Kerala Seafood',
    category: 'Non-Veg',
    description: 'Dine in a houseboat-themed restaurant with authentic Kerala cuisine.',
    address: 'Kundannoor, Maradu, Kochi, Kerala 682304, India',
    phone: '+91 484 270 5703',
    location: { lat: 9.943, lng: 76.324 },
    heroImage: findImage('new-spot-35-hero'),
    gallery: [findImage('new-spot-35-gallery-1'), findImage('new-spot-35-gallery-2')],
  },
  {
    id: 'palaaram',
    name: 'Palaaram',
    cuisine: 'Kerala Snacks, Cafe',
    category: 'Mixed',
    description: 'Specializes in traditional Kerala snacks, both sweet and savory.',
    address: 'Kadavanthra, Kochi, Kerala 682020, India',
    phone: '+91 9895 180 000',
    location: { lat: 9.970, lng: 76.305 },
    heroImage: findImage('new-spot-43-hero'),
    gallery: [findImage('new-spot-43-gallery-1'), findImage('new-spot-43-gallery-2')],
  },
  {
    id: 'chai-cofi',
    name: 'Chai Cofi',
    cuisine: 'Cafe, Tea House',
    category: 'Mixed',
    description: 'A trendy spot for tea lovers, offering a variety of chai and coffee.',
    address: 'Kaloor, Kochi, Kerala 682017, India',
    phone: '+91 9846 166 660',
    location: { lat: 9.995, lng: 76.295 },
    heroImage: findImage('new-spot-13-hero'),
    gallery: [findImage('new-spot-13-gallery-1'), findImage('new-spot-13-gallery-2')],
  },
  {
    id: 'fort-cochin-sea-food',
    name: 'Fort Cochin Sea Food Restaurant',
    cuisine: 'Seafood',
    category: 'Non-Veg',
    description: 'Dine on the day\'s catch right by the famous Chinese fishing nets.',
    address: 'Fort Kochi Beach, Kochi, Kerala 682001, India',
    phone: '+91 9847 244 440',
    location: { lat: 9.969, lng: 76.239 },
    heroImage: findImage('new-spot-47-hero'),
    gallery: [findImage('new-spot-47-gallery-1'), findImage('new-spot-47-gallery-2')],
  },
  {
    id: 'east-india-street-cafe',
    name: 'East India Street Cafe',
    cuisine: 'Cafe, International',
    category: 'Mixed',
    description: 'A beautiful cafe with a colonial vibe and a menu of international dishes.',
    address: 'Mattancherry, Kochi, Kerala 682002, India',
    phone: '+91 484 222 3333',
    location: { lat: 9.958, lng: 76.251 },
    heroImage: findImage('new-spot-46-hero'),
    gallery: [findImage('new-spot-46-gallery-1'), findImage('new-spot-46-gallery-2')],
  },
  {
    id: 'sky-grill-lounge',
    name: 'Sky Grill Lounge Bar',
    cuisine: 'Lounge, Continental',
    category: 'Mixed',
    description: 'A rooftop restaurant offering panoramic views of the city and a lounge atmosphere.',
    address: 'Crowne Plaza, Maradu, Kochi, Kerala 682304, India',
    phone: '+91 484 286 5000',
    location: { lat: 9.939, lng: 76.326 },
    heroImage: findImage('new-spot-44-hero'),
    gallery: [findImage('new-spot-44-gallery-1'), findImage('new-spot-44-gallery-2')],
  },
  {
    id: 'the-burger-junction',
    name: 'The Burger Junction',
    cuisine: 'Burgers, Fast Food',
    category: 'Mixed',
    description: 'A popular spot for gourmet burgers and sliders.',
    address: 'Panampilly Nagar, Kochi, Kerala 682036, India',
    phone: '+91 95676 72777',
    location: { lat: 9.962, lng: 76.294 },
    heroImage: findImage('new-spot-1-hero'),
    gallery: [findImage('new-spot-1-gallery-1'), findImage('new-spot-1-gallery-2')],
  },
  {
    id: 'cocoa-tree',
    name: 'Cocoa Tree',
    cuisine: 'Cafe, Desserts',
    category: 'Mixed',
    description: 'A favorite among locals for its delicious desserts, pastries, and cafe fare.',
    address: 'The Avenue Regent, MG Road, Kochi, Kerala 682016, India',
    phone: '+91 484 406 0000',
    location: { lat: 9.981, lng: 76.291 },
    heroImage: findImage('new-spot-11-hero'),
    gallery: [findImage('new-spot-11-gallery-1'), findImage('new-spot-11-gallery-2')],
  },
  {
    id: 'pizza-italia',
    name: 'Pizza Italia',
    cuisine: 'Italian, Pizza',
    category: 'Mixed',
    description: 'Serving authentic wood-fired pizzas in the heart of Fort Kochi.',
    address: 'Rose Street, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 9847 872 735',
    location: { lat: 9.966, lng: 76.244 },
    heroImage: findImage('new-spot-7-hero'),
    gallery: [findImage('new-spot-7-gallery-1'), findImage('new-spot-7-gallery-2')],
  },
  {
    id: 'rasoi-fort-kochi',
    name: 'Rasoi Fort Kochi',
    cuisine: 'North Indian, Seafood',
    category: 'Mixed',
    description: 'A restaurant offering a mix of North Indian flavors and fresh local seafood.',
    address: 'Chirattapalam, Fort Kochi, Kochi, Kerala 682001, India',
    phone: '+91 484 221 5005',
    location: { lat: 9.963, lng: 76.241 },
    heroImage: findImage('new-spot-45-hero'),
    gallery: [findImage('new-spot-45-gallery-1'), findImage('new-spot-45-gallery-2')],
  },
  {
    id: 'grand-pavilion',
    name: 'Grand Pavilion',
    cuisine: 'Multi-Cuisine',
    category: 'Mixed',
    description: 'A classic restaurant in a heritage hotel, known for its Syrian Christian dishes.',
    address: 'Grand Hotel, MG Road, Kochi, Kerala 682011, India',
    phone: '+91 484 238 2061',
    location: { lat: 9.973, lng: 76.287 },
    heroImage: findImage('new-spot-36-hero'),
    gallery: [findImage('new-spot-36-gallery-1'), findImage('new-spot-36-gallery-2')],
  },
  {
    id: 'tonico-cafe',
    name: 'Tonico Cafe',
    cuisine: 'Cafe, International',
    category: 'Mixed',
    description: 'A modern, vibrant cafe popular with a younger crowd for its food and ambiance.',
    address: 'Kakkanad, Kochi, Kerala 682030, India',
    phone: '+91 9072 888 885',
    location: { lat: 10.015, lng: 76.358 },
    heroImage: findImage('new-spot-1-hero'),
    gallery: [findImage('new-spot-1-gallery-1'), findImage('new-spot-1-gallery-2')],
  },
  {
    id: 'the-voyage',
    name: 'The Voyage',
    cuisine: 'Cafe',
    category: 'Mixed',
    description: 'A travel-themed cafe that attracts explorers and foodies alike.',
    address: 'Panampilly Nagar, Kochi, Kerala, India',
    phone: '+91 9072 333 433',
    location: { lat: 9.963, lng: 76.295 },
    heroImage: findImage('new-spot-33-hero'),
    gallery: [findImage('new-spot-33-gallery-1'), findImage('new-spot-33-gallery-2')],
  },
  {
    id: 'raw-squeeze',
    name: 'Raw Squeeze',
    cuisine: 'Juice Bar, Healthy',
    category: 'Veg',
    description: 'A popular spot for fresh cold-pressed juices, smoothies, and healthy bowls.',
    address: 'Kadavanthra, Kochi, Kerala, India',
    phone: '+91 9567 444 422',
    location: { lat: 9.972, lng: 76.306 },
    heroImage: findImage('new-spot-37-hero'),
    gallery: [findImage('new-spot-37-gallery-1'), findImage('new-spot-37-gallery-2')],
  },
  {
    id: 'farmers-cafe',
    name: 'Farmer\'s Cafe',
    cuisine: 'Healthy, Organic',
    category: 'Veg',
    description: 'A cafe focused on organic and farm-to-table ingredients.',
    address: 'Kadavanthra, Kochi, Kerala, India',
    phone: '+91 484 404 0444',
    location: { lat: 9.971, lng: 76.307 },
    heroImage: findImage('new-spot-14-hero'),
    gallery: [findImage('new-spot-14-gallery-1'), findImage('new-spot-14-gallery-2')],
  },
  {
    id: 'the-wok-republic',
    name: 'The Wok Republic',
    cuisine: 'Pan-Asian',
    category: 'Mixed',
    description: 'A modern take on Asian street food with a make-your-own-bowl concept.',
    address: 'Kaloor, Kochi, Kerala, India',
    phone: '+91 9061 988 888',
    location: { lat: 9.996, lng: 76.296 },
    heroImage: findImage('new-spot-10-hero'),
    gallery: [findImage('new-spot-10-gallery-1'), findImage('new-spot-10-gallery-2')],
  },
  {
    id: 'tiki-taco',
    name: 'Tiki Taco by The Burger Junction',
    cuisine: 'Mexican',
    category: 'Mixed',
    description: 'Serving up delicious tacos, burritos, and other Mexican favorites.',
    address: 'Panampilly Nagar, Kochi, Kerala, India',
    phone: '+91 95676 72777',
    location: { lat: 9.962, lng: 76.293 },
    heroImage: findImage('new-spot-18-hero'),
    gallery: [findImage('new-spot-18-gallery-1'), findImage('new-spot-18-gallery-2')],
  },
  {
    id: 'loaf-story',
    name: 'Loaf Story',
    cuisine: 'Bakery, Cafe',
    category: 'Mixed',
    description: 'An artisanal bakery known for its sourdough bread and delicious pastries.',
    address: 'Panampilly Nagar, Kochi, Kerala, India',
    phone: '+91 9072 323 232',
    location: { lat: 9.964, lng: 76.294 },
    heroImage: findImage('new-spot-11-hero'),
    gallery: [findImage('new-spot-11-gallery-1'), findImage('new-spot-11-gallery-2')],
  },
  {
    id: 'the-history-restaurant',
    name: 'The History Restaurant',
    cuisine: 'Fine Dining, Kerala',
    category: 'Mixed',
    description: 'A restaurant in a boutique hotel that takes you on a culinary journey through Kerala\'s history.',
    address: 'Brunton Boatyard, Fort Kochi, Kochi, Kerala, India',
    phone: '+91 484 221 5461',
    location: { lat: 9.969, lng: 76.239 },
    heroImage: findImage('new-spot-19-hero'),
    gallery: [findImage('new-spot-19-gallery-1'), findImage('new-spot-19-gallery-2')],
  },
  {
    id: 'sri-krishna-inn',
    name: 'Sri Krishna Inn',
    cuisine: 'Vegetarian, South Indian',
    category: 'Veg',
    description: 'A pure vegetarian spot beloved for its crispy dosas and comforting thalis.',
    address: 'Warriam Road, Pallimukku, Kochi, Kerala, India',
    phone: '+91 484 236 8577',
    location: { lat: 9.974, lng: 76.289 },
    heroImage: findImage('new-spot-3-hero'),
    gallery: [findImage('new-spot-3-gallery-1'), findImage('new-spot-3-gallery-2')],
  },
  {
    id: 'the-drawing-room',
    name: 'The Drawing Room',
    cuisine: 'Lounge, Cafe',
    category: 'Mixed',
    description: 'A serene and artistic lounge inside the Cochin Club.',
    address: 'Cochin Club, Fort Kochi, Kochi, Kerala, India',
    phone: '+91 484 221 5191',
    location: { lat: 9.968, lng: 76.242 },
    heroImage: findImage('new-spot-48-hero'),
    gallery: [findImage('new-spot-48-gallery-1'), findImage('new-spot-48-gallery-2')],
  },
  {
    id: 'paulose-toddy-shop',
    name: 'Paulose Toddy Shop',
    cuisine: 'Toddy Shop',
    category: 'Non-Veg',
    description: 'A traditional toddy shop experience with fiery local dishes.',
    address: 'Thiruvankulam, Kochi, Kerala, India',
    phone: '+91 9847 111 222',
    location: { lat: 9.955, lng: 76.355 },
    heroImage: findImage('new-spot-31-hero'),
    gallery: [findImage('new-spot-31-gallery-1'), findImage('new-spot-31-gallery-2')],
  },
  {
    id: 'kebab-grill-house',
    name: 'Kebab Grill House',
    cuisine: 'Turkish, Kebab',
    category: 'Non-Veg',
    description: 'Serving authentic Turkish kebabs and grills.',
    address: 'Palarivattom, Kochi, Kerala, India',
    phone: '+91 9895 333 444',
    location: { lat: 10.008, lng: 76.308 },
    heroImage: findImage('new-spot-50-hero'),
    gallery: [findImage('new-spot-50-gallery-1'), findImage('new-spot-50-gallery-2')],
  },
  {
    id: 'pind-balluchi',
    name: 'Pind Balluchi',
    cuisine: 'North Indian, Punjabi',
    category: 'Mixed',
    description: 'A themed restaurant that brings the flavors of a Punjabi village to Kochi.',
    address: 'Vyttila, Kochi, Kerala, India',
    phone: '+91 484 401 1111',
    location: { lat: 9.975, lng: 76.315 },
    heroImage: findImage('dal-roti-hero'),
    gallery: [findImage('dal-roti-gallery-1'), findImage('dal-roti-gallery-2')],
  },
  {
    id: 'the-good-bowl',
    name: 'The Good Bowl',
    cuisine: 'Healthy Bowls',
    category: 'Mixed',
    description: 'A delivery-focused kitchen offering a variety of healthy and hearty meal bowls.',
    address: 'Kakkanad, Kochi, Kerala, India',
    phone: '+91 9061 111 222',
    location: { lat: 10.014, lng: 76.359 },
    heroImage: findImage('new-spot-25-hero'),
    gallery: [findImage('new-spot-25-gallery-1'), findImage('new-spot-25-gallery-2')],
  },
  {
    id: 'french-toast-kochi',
    name: 'French Toast',
    cuisine: 'Bakery, Cafe',
    category: 'Mixed',
    description: 'A patisserie and cafe specializing in French pastries, desserts, and of course, French toast.',
    address: 'Panampilly Nagar, Kochi, Kerala, India',
    phone: '+91 9847 000 999',
    location: { lat: 9.966, lng: 76.297 },
    heroImage: findImage('new-spot-11-hero'),
    gallery: [findImage('new-spot-11-gallery-1'), findImage('new-spot-11-gallery-2')],
  },
  {
    id: 'palluruthy-seafood-house',
    name: 'Palluruthy Seafood House',
    cuisine: 'Kerala Seafood',
    category: 'Non-Veg',
    description: 'A local gem in Palluruthy known for its fresh catch of the day and traditional spicy preparations.',
    address: 'Palluruthy, Kochi, Kerala 682006, India',
    phone: '+91 9847 555 666',
    location: { lat: 9.925, lng: 76.275 },
    heroImage: findImage('new-spot-51-hero'),
    gallery: [findImage('new-spot-51-gallery-1'), findImage('new-spot-51-gallery-2')],
  },
  {
    id: 'ernakulam-kitchen-delights',
    name: 'Ernakulam Kitchen Delights',
    cuisine: 'Multi-Cuisine',
    category: 'Mixed',
    description: 'A bustling eatery in the heart of Ernakulam city, serving a mix of Kerala, North Indian, and Chinese dishes.',
    address: 'MG Road, Ernakulam, Kochi, Kerala 682016, India',
    phone: '+91 484 237 7777',
    location: { lat: 9.980, lng: 76.290 },
    heroImage: findImage('new-spot-52-hero'),
    gallery: [findImage('new-spot-52-gallery-1'), findImage('new-spot-52-gallery-2')],
  },
  {
    id: 'edappally-food-court',
    name: 'Edappally Food Court',
    cuisine: 'Food Court',
    category: 'Mixed',
    description: 'A popular hub with multiple food stalls offering a wide variety of cuisines to suit every palate.',
    address: 'Near Lulu Mall, Edappally, Kochi, Kerala 682024, India',
    phone: '+91 484 292 9999',
    location: { lat: 10.028, lng: 76.310 },
    heroImage: findImage('new-spot-53-hero'),
    gallery: [findImage('new-spot-53-gallery-1'), findImage('new-spot-53-gallery-2')],
  }
];

export const restaurants: Restaurant[] = allRestaurants.filter(r => r.address.includes('Kochi'));


    

    

    
